// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BreathingController from "./breathing_controller"
application.register("breathing", BreathingController)

import ExerciseController from "./exercise_controller"
application.register("exercise", ExerciseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QuotesController from "./quotes_controller"
application.register("quotes", QuotesController)
